os: osx
language: generic
osx_image: xcode9.3beta

#services:
#  - docker

#before_install:
#  - docker pull eclipse-mosquitto
#  - docker run -dp 1883:1883 eclipse-mosquitto

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - swift test
