#sudo: required

language: objective-c
osx_image: xcode9.2

#services:
#  - docker

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'

#before_install:
#  - docker pull eclipse-mosquitto
#  - docker run -p 1883:1883 eclipse-mosquitto
script:
  - set -o pipefail && xcodebuild -scheme MQTTKit -destination "$DESTINATION" $ACTION | xcpretty
